export const RPC_HYPER_INIT = 1
export const RPC_HYPER_FETCH = 2
export const RPC_HYPER_CREATE_DRIVE = 3
export const RPC_HYPER_STORAGE_LIST = 4
export const RPC_HYPER_STORAGE_DELETE_APP = 5
export const RPC_HYPER_STORAGE_CLEAR_CACHE = 6
export const RPC_HYPER_LAN_STATUS = 7

export const RPC_HOLESAIL_START_LIVE = 10
export const RPC_HOLESAIL_CONNECT = 11
export const RPC_HOLESAIL_STATUS = 12
export const RPC_HOLESAIL_STOP = 13

export const RPC_P2PMD_ROOM_CREATE = 20
export const RPC_P2PMD_ROOM_STATUS = 21
export const RPC_P2PMD_ROOM_DISCONNECT = 22
export const RPC_P2PMD_ROOM_JOIN = 23
export const RPC_P2PMD_ROOM_PUBLISH = 24
export const RPC_P2PMD_EDITOR_PAGE = 25
export const RPC_P2PMD_PREVIEW = 26
export const RPC_P2PMD_IMAGE_UPLOAD = 27

export const RPC_IDENTITY_GET_KEY = 30
export const RPC_IDENTITY_RESTORE_FROM_HYPER = 31
export const RPC_IDENTITY_CONFIRM_RESTORE = 32
